project:
  type: website
  output-dir: docs

website:
  title: "The Waddington Code"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/josef-bryja-024140291/
      - icon: github
        href: https://github.com/JosefBryja
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



